import type { Metadata } from "next";
import "./globals.css";
import { NavigationBar } from "@/components/ui/NavigationBar";
import { AuthProvider } from "@/components/auth/AuthProvider";
import { QueryProvider } from "./providers";

export const metadata: Metadata = {
  title: "CodeOrbit",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
            <NavigationBar />
            <QueryProvider>
                {children}
            </QueryProvider>
        </AuthProvider>          
      </body>
    </html>
  );
}